spring.application.name=expbackend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/expense_tracker_db
spring.datasource.username=postgres
spring.datasource.password=pooja2558
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.servlet.context-path=/
server.port=8080
debug=true
# Response compression
server.compression.enabled=true
server.compression.min-response-size=1024

# JWT Configuration
jwt.secret=mySecretKeyForExpenseTrackerApplicationPleaseChangeThisInProduction1234567890
jwt.expiration=86400000



